Recipe/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from posts import views

urlpatterns = [
     path('admin/', admin.site.urls),


     path('accounts/', include('accounts.urls')),
     path('accounts/', include('django.contrib.auth.urls')),
     path('', include('posts.urls')),
     path('guest_home/', include('guest_home.urls')),
     path('user_profile/', include('user_profile.urls')),
     path('comments/', include('comments.urls')),
     path('social-auth/', include('social_django.urls', namespace="social")),
     # path('<int:recipe_id>/like/', views.like_post, name='like_post'),
     path('<int:id>', views.like_post, name="like_post"),
     #path('like/', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

comments/urls.py
from django.urls import path

#from posts.views import HomePageView, CreatePostView
from . import views
from .views import HomePageView, CreatePostView
from . import views

urlpatterns = [
    #path('', HomePageView.as_view(), name='more_new'),
    #path('post/', CreatePostView.as_view(), name='add_post'),
    #path('<int:id>/', views.CreateMoreView, name='more_new'),
   # path('<int:id>/', views.CreateMoreView, name='more_new'),
    path('comments/', CreatePostView.as_view(), name='add_post'),
    path('', HomePageView.as_view(), name='more_new'),
    path('logout/', views.logout, name='logout'),

    #path('post/', CCreatePostView.as_view(), name='add_post'),
    #path('<int:id>/', views.CCreateMoreView, name='more_new'),

]

guest_home/urls.py
from django.urls import path

from posts.views import GuestHomePageView


urlpatterns = [
    path('', GuestHomePageView.as_view(), name='guest_home'),
    #path('', GuestHomePageView.as_view, name='guest_home')
]

posts/urls.py
from django.urls import path

from .views import HomePageView, CreatePostView, like_post
from . import views

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('post/', CreatePostView.as_view(), name='add_post'),
    path('<int:id>/', views.CreateMoreView, name='more_new'),

]

comments/models.py
from django.db import models

# Create your models here.

from django.db import models

from posts.models import Post
'''class Comment(models.Model):

    comment = models.TextField(null='True')
    user_id = models.ForeignKey(Post, on_delete=models.CASCADE),
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE),
    #ForeignKey(Reporter, on_delete=models.CASCADE)


    def __str__(self):
        return self.comment'''

guest_home/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=50)
    cover = models.ImageField(upload_to='images/')
    description = models.TextField(null='True')
    likes = models.ManyToManyField(User, related_name='likes', blank='True')
    author = models.ForeignKey(User,  on_delete=models.CASCADE, null='True')
    publish_date = models.DateField(null='True')
    #a =models.ManyToManyField(User,related_name='add', blank='True')

    def __str__(self):
        return' {} {} {} '.format(self.title, self.description, self.publish_date)

    def total_likes(self):
        return self.likes.count()
    '''def likes_name(self):
        return self.likes.username'''


'''class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models)
    user = models.ForeignKey(User, on_delete=models)
    content = models.TextField(max_length=160)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return'{} {}'.format(self.post.title, str(self.user.username))'''

user_profile/models.py
from django.db import models


class Upload(models.Model):
    title = models.TextField(null='True')
    cover = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

comments/forms.py
from django import forms
from posts.models import Post



class DateInput(forms.DateInput):
    input_type = 'date'

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'cover',  'description', 'publish_date']
        widgets = {
            'publish_date': DateInput(),
        }


#from .models import Comment

class PostComment(forms.ModelForm):

    class Meta:
        #model = Comment
        fields = ['comment']

posts/forms.py
from django import forms
from .models import Post



class DateInput(forms.DateInput):
    input_type = 'date'

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'cover', 'description', 'publish_date']
        widgets = {
             'publish_date': DateInput(),
         }



'''class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)'''

user_profile/forms.py
from django import forms
from .models import Upload

class PostForm(forms.ModelForm):

    class Meta:
        model = Upload
        fields = ['title', 'cover']

comments/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect
from django.contrib import auth




from .forms import PostComment
#from .models import Comment

class HomePageView(ListView):
    #model = Comment
    template_name = 'more_new.html'

class CreatePostView(CreateView):
    #model = Comment
    form_class = PostComment
    template_name = 'comment.html'
    success_url = reverse_lazy('more_new')

def logout(request):
    auth.logout(request)
    # Redirect to a success page.
    return HttpResponseRedirect("/accounts/login")

'''
def CreateMoreView(request, id):
    post = Comment.objects.get(id=id)

    context = {

        'post': post

    }

    return render(request, 'more_new.html', context)

'''

guest_home/views.py
from django.views.generic import ListView

from posts.models import Post

class GuestHomePageView(ListView):
    model = Post
    template_name = 'guest_home.html'

posts/views.py
from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy
from django.shortcuts import render

from django.http import HttpResponse
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import HttpResponseRedirect

from .forms import PostForm
from .models import Post

from django.core.mail import send_mail


class HomePageView(ListView):
    model = Post
    template_name = 'home.html'

class CreatePostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'post.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        f = form.save(commit=False)
        f.author = self.request.user
        f.save()
        return super(CreatePostView, self).form_valid(form)

    '''def like_post(request):
        post = get_object_or_404(Post, id=request.POST.get('post_id'))
        post.likes.add(request.user)
        return HttpResponse(Post.get_absolute_url())'''


def CreateMoreView(request, id):
    post = Post.objects.get(id=id)
    #comments = Comment.objects.filter(post=post).order_by('-id')
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True

    context = {

        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
        #'liked_names' : post.likes_name(),
        #'comment': comments,


    }
    #post = get_object_or_404(Post, id=request.POST.get('post_id'))
    #post.likes.add(request.user)
    return render(request, 'more_new.html', context)


def like_post(request, id):

    post = Post.objects.get(id=id)
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True
    context = {
                'post': post,
                'is_liked': is_liked,

                }
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
        is_liked = True
    post.likes.add(request.user)
    return render(request, 'more_new.html', context)


class GuestHomePageView(ListView):
    model = Post
    template_name = 'guest_home.html'

class PromiseCreateView(CreateView):
    model = Post
    form_class = 'PostForm'

user_profile/views.py
from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy

from .forms import PostForm
from .models import Upload

class HomePageView(ListView):
    model = Upload
    template_name = 'user_profile.html'

class CreatePostView(CreateView):
    model = Upload
    form_class = PostForm
    template_name = 'post1.html'
    success_url = reverse_lazy('user_profile')

templates/base.html
{% load staticfiles %}
<html>
<head>


<script>
function myFunction() {
  alert("Log in as a new user");
}

function change( el )
{
    if ( el.value === "Like" )
        el.value = "Unlike";
    else
        el.value = "Like";
}



</script>
<style>
.body {
  background-color : #FFF8dc

  }

.footer {
  position: relative;
  right: 0;
  bottom: 0;
  left: 0;
  padding: 1rem;
  background-color: #efefef;
  text-align: center;
}

#page-container {
  position: relative;
  min-height: 100vh;
}

#content-wrap {
  padding-bottom: 2.5rem;
}





</style>
   <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>





  <title>{% block title %}Recipe web app{% endblock %}</title>
</head>



<body class="body">


<nav class="navbar navbar-dark bg-dark">
 <!-- <span class="navbar-toggler-icon"></span>-->
    <span  ><a href="http://localhost:8000/guest_home/"    class="navbar-branch btn btn-info navbar-left"  style="color:white">Recipe web</a></span>


  <ul class="nav navbar-nav navbar-right">



        <a class="btn btn-outline-success" type="button"  href="{% url 'login'%}"> &nbsp &nbsp &nbsp &nbsp LOGIN &nbsp &nbsp &nbsp &nbsp </button></a>

    </ul>


</nav>







 <div id="page-container">
   <div id="content-wrap">


 <div class="container">

      <div class="row justify-content-center">
        <div class="col-11">
          <h1 class="mt-0"></h1>
          <hr class="mt-0 mb-2">

  <main>
    {% block content %}
    {% endblock %}
  </main>
          </div>
      </div>
    </div>
 </div>



</div>

<div class="footer"><b>Recipe web </b> is built for sharing your own recipe to others. </div>

</div>


</body>
</html>

templates/comment.html
<h1>Create Post Page</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit New comment</button>
</form>

templates/form-template.html
{% for field in form %}
    <div class="form-group">
        <label style="font-size: 20px;color: white; " >{{ field.label_tag }}</label>
        <div class="input" >{{ field }}</div>
    </div>
{% endfor %}

templates/guest_base.html
<!DOCTYPE html>
<html>
<head>

<style>
.body {
  background-color : #FFF8dc

  }

.footer {
  position: relative;
  right: 0;
  bottom: 0;
  left: 0;
  padding: 1rem;
  background-color: #efefef;
  text-align: center;
}

#page-container {
  position: relative;
  min-height: 100vh;
}

#content-wrap {
  padding-bottom: 2.5rem;
}





</style>
   <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>





  <title>{% block title %}Recipe web app{% endblock %}</title>
</head>



<body class="body">


<nav class="navbar navbar-dark bg-dark">
 <!-- <span class="navbar-toggler-icon"></span>-->
    <span class="navbar-branch navbar-left" style="color:white">Recipe web</span>

    <form class="form-inline">
<!--    <a class="btn btn-outline-info" type="button" href="">SHARE YOUR RECIPE</a> &nbsp &nbsp &nbsp &nbsp
-->

  </form>
  <ul class="nav navbar-nav navbar-right">



 <a class="btn btn-success"  href="{% url 'login'%}" >LOGIN</a>


    </ul>


</nav>



   <div id="content-wrap">


 <div class="container">

      <div class="row justify-content-center">
        <div class="col-11">
          <h1 class="mt-0"></h1>
          <hr class="mt-0 mb-2">

  <main>
    {% block content %}
    {% endblock %}
  </main>
          </div>
      </div>
    </div>
 </div>



</div>

<div class="footer"><b>Recipe web </b> is built for sharing your own recipe to others. </div>

</div>


</body>
</html>

templates/guest_home.html
{% extends 'guest_base.html' %}
{% block title %}Guest_Home{% endblock %}
{% block content %}

<h1><center>MY RECIPE</center></h1>






 <div id="page-container">

<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">WELCOME</h4>
  <p>This is website which where you can post your recipe.</p>
  <hr>
  <p class="mb-0">And also see others posts</p>
</div>



<div class="card" style="width: 40rem;">


  {% for post in object_list %}
    <h2>{{ post.title }}</h2>
  <h3>posted : {{ post.author }}</h3>

  <h4> date : {{ post.publish_date }}</h4>
<div class="card-body">
    <img   class="card-img-top"  src="{{ post.cover.url}}" alt="{{ post.title }}">




    <hr>
  {% endfor %}


  </div>
  </div>
</div>





{% endblock %}

templates/logout2.html
{% extends 'base.html' %}

{% block title %}Logout{% endblock %}

{% block content %}




 <div id="page-container">

<div class="alert alert-success" role="alert">
  <h4 class="alert-heading">successfully logged out</h4>
  <p>This is website which where you can post your recipe.</p>
  <hr>
  <p class="mb-0">And also see others posts</p>
</div>
 </div>


  <p>successfully logged out</p>
  <a class="btn btn-info" href="{% url 'login' %}">login</a>



{% endblock %}

templates/more.html
{% extends 'post_base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<h1><center>ABOUT THIS RECIPE </center></h1>




<div class="card" style="width: 40rem;">


<div class="row">
    <div class="col-md-12">

    <img   class="card-img-top"  src="{{ post.cover.url}}" alt="{{ post.title }}">






    <div class="col-md-12">
        <h5>Name of Recipe:</h5>
       <h2>{{ post.title }}</h2>
        <br>
        <h5>Description:</h5>
       <h2>{{ post.description }}</h2>



        <h5>Rate this Recipe :</h5>




<!--progress-->

     <button data-toggle="progressbar" data-target="#myProgressbar" data-value="reset" data-level="info" class="btn btn-default">Reset</button>
            <button data-toggle="progressbar" data-target="#myProgressbar" data-value="0" class="btn btn-default">0%</button>
            <button data-toggle="progressbar" data-target="#myProgressbar" data-value="10" class="btn btn-default">10%</button>
            <button data-toggle="progressbar" data-target="#myProgressbar" data-value="30" class="btn btn-default">30%</button>
            <button data-toggle="progressbar" data-target="#myProgressbar" data-value="75" class="btn btn-default">75%</button>
            <button data-toggle="progressbar" data-target="#myProgressbar" data-value="100" class="btn btn-default">100%</button>

        </p>

        <div id="myProgressbar" class="progress">
          <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
            <span class="sr-only">0% Complete</span>
          </div>
        </div>


    <script src="https://code.jquery.com/jquery.js"></script>
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

<!--ebuttonnd progress-->


    </div>


</div>



</div>

</div>



{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}


<script>


!function ($) {

    "use strict";

    // PROGRESSBAR CLASS DEFINITION
    // ============================

    var Progressbar = function (element) {
        this.$element = $(element);
    }

    Progressbar.prototype.update = function (value) {
        var $div = this.$element.find('div');
        var $span = $div.find('span');
        $div.attr('aria-valuenow', value);
        $div.css('width', value + '%');
        $span.text(value + '% Complete');
    }

    Progressbar.prototype.finish = function () {
        this.update(100);
    }

    Progressbar.prototype.reset = function () {
        this.update(0);
    }

    // PROGRESSBAR PLUGIN DEFINITION
    // =============================

    $.fn.progressbar = function (option) {
        return this.each(function () {
            var $this = $(this),
                data = $this.data('jbl.progressbar');

            if (!data) $this.data('jbl.progressbar', (data = new Progressbar(this)));
            if (typeof option == 'string') data[option]();
            if (typeof option == 'number') data.update(option);
        })
    };

    // PROGRESSBAR DATA-API
    // ====================

    $(document).on('click', '[data-toggle="progressbar"]', function (e) {
        var $this = $(this);
        var $target = $($this.data('target'));
        var value = $this.data('value');

        e.preventDefault();

        $target.progressbar(value);
    });

}(window.jQuery);






</script>




{% endblock %}

templates/post.html
{% extends 'post_base_new.html' %}
{%load staticfiles%}

{% block title %}CookBook_post{% endblock %}

{% if user.is_authenticated %}

{% block content %}
<html>

<head>

    <script language="javascript">
    function myFunction(){
setTimeout(function(){
   window.location.reload(1);
}, 200);}
</script>

    <!-- Required Meta Tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Page Title -->
    <title>CookBook2019</title>

    <!-- Favicon -->

    <link rel="shortcut icon" href="{% static 'assets/images/logo/favicon.png' %}" >

    <!-- CSS Files -->
    <link rel="stylesheet" href="{% static 'assets/css/animate-3.7.0.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/font-awesome-4.7.0.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/bootstrap-4.1.3.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl-carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/jquery.datetimepicker.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
</head>

<body>


<!-- Preloader Starts -->
    <div class="preloader">
        <div class="spinner"></div>
    </div>
    <!-- Preloader End -->

    <!-- Header Area Starts -->
	<header class="header-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                    <div class="logo-area">

                        <!--<a href="index.html"><img src="{% static 'assets/images/logo/logo1.png' %}" alt="logo"></a>

-->
                         <a href="/user_profile/" class="btn btn-info"><img alt="">{{ user.username}}</a>
                    </div>
                </div>
                <div class="col-lg-10">
                    <div class="custom-navbar">
                        <span></span>
                        <span></span>
                        <span></span>
                    </div>
                    <div class="main-menu">
                        <ul>
                            <li class="active"><a href="http://localhost:8000/ ">home</a></li>
                            <!--<li><a href="/user_profile/">Profile</a></li>-->
                            <li><a href="/post/">Post</a></li>
                           <!-- <li><a href="#">blog</a>
                                <ul class="sub-menu">
                                    <li><a href="blog-home.html">Blog Home</a></li>
                                    <li><a href="blog-details.html">Blog Details</a></li>
                                </ul>
                            </li>-->
                           <!-- <li><a href="contact-us.html">contact</a></li>-->

                            <li><a class="btn btn-info" href="{% url 'login'%}"  onclick="myFunction()" >Logout</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Area End -->

    <!-- Banner Area Starts -->
    <section class="banner-area text-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h6>the most interesting food in the world</h6>
                    <h1>Discover the <span class="prime-color">flavors</span><br>
                    <span class="style-change">of <span class="prime-color">Cook</span>Book</span></h1>
                </div>
            </div>
        </div>
    </section>
    <!-- Banner Area End -->

    <!-- Welcome Area Starts -->
    <section class="welcome-area section-padding2">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 align-self-center">
                    <div class="welcome-img">
                        <img src="{% static 'assets/images/welcome-bg.png' %}" class="img-fluid" alt="">
                    </div>
                </div>
                <div class="col-md-6 align-self-center">
                    <div class="welcome-text mt-5 mt-md-0">
                        <h3><span class="style-change">welcome to </span>Cook<br>Book</h3>
                        <p class="pt-3">Creatye your recipe and share your recipe to others </p>
                        <p>see what others have been posted</p>
                        <a href="#" class="template-btn mt-3">Post Your Recipe Secret</a>

                        </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Welcome Area End -->


    <!-- Reservation Area Starts -->
    <div class="reservation-area section-padding text-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">


<form  method="post" enctype="multipart/form-data">
    {% csrf_token %}



    <input type="title" class="form-control" id="id_title" name="title" placeholder="title " required="" maxlength="50"><br><br>



    <div class="custom-file">
    <input type="file" class="custom-file-input" id="id_cover" name="cover"
       placeholder="choose file" required="">
    <label class="custom-file-label" for="id_cover" >Choose file</label>
    </div><br><br>

    <input id ="id_description" name="description" class="form-control form-control-lg" placeholder="Write about it" cols="40" required="" rows="10"><br><br>

    <input id="id_publish_date" name="publish_date" type="date" class="form-control form-control" placeholder="Write about it" ><br><br>




    <input type="submit" value="Submit" class="btn btn-success" >
</form>




                </div>
            </div>
        </div>
    </div>
    <!-- Reservation Area End -->


    <!-- Update Area Starts -->


    <section class="update-area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-top2 text-center">
                        <h3>Our <span>food</span> update</h3>
                        <p><i>Beast kind form divide night above let moveth bearing darkness.</i></p>
                    </div>
                </div>
            </div>
            <div class="row">
            </div>
        </div>
    </section>
    <!-- Footer Area Starts -->
    <footer class="footer-area">

        <div class="footer-copyright">
            <div class="container">
                <div class="row">
                    <div class="col-lg-7 col-md-6">
                        <span>
Copyright &copy;no rights reserved <class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://tarams.com" target="_blank">website</a>
</span>
                    </div>
                    <div class="col-lg-5 col-md-6">
                        <div class="social-icons">
                            <ul>
                                <li class="no-margin">Follow Us</li>
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-pinterest"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Area End -->


    <!-- Javascript -->
    <script src="{% static 'assets/js/vendor/jquery-2.2.4.min.js' %}"></script>
	<script src="{% static 'assets/js/vendor/bootstrap-4.1.3.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/wow.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/owl-carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery.datetimepicker.full.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'assets/js/main.js' %}"></script>


</body>
</html>

{% endblock %}


{% else %}
  <p><script> alert("you sre not login")</script></p>
  <a class="btn btn-info" href="{% url 'login' %}">login</a>
{% endif %}

templates/post1.html
<h1>Create Post Page</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit New Post</button>
</form>

templates/user_page.html
<html>
<head>

</head>


    <style>
        body{
            background-color: #2b542c;
        }

        h1{
              color: white;
              background-color:#4cae4c;
              width: 100%;
              float:left;
              height: 50px;
        }

        button{
            width: auto;
            height: 40px;
            text-align: center;
            background-color: #1b6d85;
            color: #ffffff;
            font-size: 30px;
            margin-top: 20px;
        }
    </style>


<body >

<h1>Add a new User</h1>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'form-template.html' %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
    </div>
</form>

</body>


</html>